# Disable sudo to speed up the build
sudo: false

language: python

python:
  - "3.9"

# Install the pip dependencies
install:
  - pip install -r requirements.txt

# Run the unit test
script:
  - pytest --cov=spps/

cache: pip

after_success:
  - coveralls
