# Disable sudo to speed up the build
sudo: false

language: python

python:
  - "3.9"

env:
  - PYTHONPATH=src

# Install the pip dependencies
install:
  - pip install -r requirements.txt

# Run the unit test
script:
  - pytest --cov=spps/

# Enable cache
cache: pip

after_success:
  - coveralls
